apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  namespace: ftc-elasticsearch-cluster
  name: elasticsearch-master
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      component: elasticsearch
      role: master
