apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: ftc-elasticsearch-cluster
  name: es-data
  labels:
    component: elasticsearch
    role: data
spec:
  selector:
    matchLabels:
      component: elasticsearch
      role: data
  serviceName: elasticsearch-data
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      - name: fix-the-volume-permission-data
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: datastorage
          mountPath: /usr/share/elasticsearch/data
      - name: fix-the-volume-permission-logs
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/logs"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: logstorage
          mountPath: /usr/share/elasticsearch/logs
      containers:
      - name: es-data
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MEMORY_LOCK 
          value: "false"
        - name: CLUSTER_NAME
          value: myesdb
        - name: NUMBER_OF_MASTERS
          value: "1"
        - name: NODE_MASTER
          value: "false"
        - name: NODE_DATA
          value: "true"
        - name: "TAKE_FILE_OWNERSHIP"
          value: "1"
        - name: NODE_INGEST
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: ES_JAVA_OPTS
          value: -Xms256m -Xmx256m #TODO this needs to be a variable based on the environment run against
        - name: DISCOVERY_SERVICE
          value: "elasticsearch-discovery.ftc-elasticsearch-cluster:9300"
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        resources:
          requests:
            cpu: 0.10
          limits:
            cpu: 1
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: http
          initialDelaySeconds: 20
          timeoutSeconds: 5
        volumeMounts:
        - name: datastorage
          mountPath: /usr/share/elasticsearch/data
        - name: logstorage
          mountPath: /usr/share/elasticsearch/logs
        - name: elasticsearch-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
      - name: elasticsearch-config
        configMap:
            name: elasticsearch-config
  volumeClaimTemplates:
  - metadata:
      name: datastorage
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi #TODO this needs a better value
      storageClassName: managed-premium
  - metadata:
      name: logstorage
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi #TODO this needs a better value
      storageClassName: managed-premium
